name: 'health_care_demo'
version: '1.0.0'
config-version: 2
dbt-cloud:
  project-id: 70403103997382

profile: 'health_care_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  health_care_demo: {}
